stages:
  - lint
  - test
  - build

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .pip-cache/
# ---------------- LINT ----------------
lint:
  stage: lint
  image: python:3.12-slim
  script:
    - pip install --quiet ruff
    - ruff check app/ tests/
    - ruff format --check app/ tests/
  allow_failure: true
  when: manual
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "main"'

# ---------------- TEST ----------------
unit-tests:
  stage: test

  image: python:3.12-slim
  before_script:
    - pip install --quiet pipenv
    - pipenv install --system --dev
  script:
    - pytest tests/ -v --tb=short -m "not docker"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "main"'
  when: manual

# ---------------- INTEGRATION TESTS (Docker) ----------------
integration-tests:
  stage: test

  image: docker:24.0

  services:
    - docker:24.0-dind

  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_HOST: "tcp://docker:2376"
    DOCKER_CERT_PATH: "/certs/client"
    CI: "true"

  before_script:
    - docker info
    - apk add --no-cache python3 py3-pip
    - pip install --quiet --break-system-packages pipenv
    - pipenv install --system --dev

  script:
    - pytest tests/ -v --tb=short --run-docker -m "not unit"

  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "main"'

  when: manual

# ---------------- BUILD (verify only) ----------------

docker-build:
  stage: build

  image: docker:24.0

  services:
    - docker:24.0-dind

  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  script:
    - docker build -t loan-prediction-backend:$CI_COMMIT_SHORT_SHA -f docker/Dockerfile .

  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

  when: manual